### PR TITLE
Updating the list command

### PR DESCRIPTION
**Pull request by chelm**
list names by default and include ids with --details

### CODE REVIEW

**Comment by pramukta** [comment]
Hmm.  This modification makes list return `None`.  But on [wamp.py:317 ](https://github.com/timbr-io/juno-magic/blob/4908ce44e3aba707c949efd0d823f07afbb5a6f4/juno_magic/extensions/wamp.py#L317)the list method is used to populate a list of ids, and that is used to make sure the selection is valid, so I think we would need to make that change as well.  Also, while a 1 to 1 mapping between Juno kernel entries and available kernel's is encouraged it's not really enforced.   That makes the list of ids returned by the WAMP call authoritative while the map fetched from the REST endpoint is really kind of best-effort.  So I think we'd also need to deal with that somehow.

It's definitely better not to show the duplicate outputs though so if we can address those issues, would be good to merge something in to address that.  Another thing in the current form people should be able to throw up a bare WAMP router and have the magics still work.  It would be really nice to keep that ability as well.

**Comment by chelm** [comment]
Ah yes, now I see. A bit tricky. By passing `details=True` to the get_kernel_names method the selection still works, but by returning not None from list() shows up in the notebook output. I'll look at that now. 

Not sure what to make of the "1 to 1" comment just yet.

**Comment by chelm** [comment]
Pushed an update to this that removes the double output and maintains the integrity of prefix_maps and the select method.

**Comment by chelm** [comment]
rebased with master

**Comment by pramukta** [comment]
Cool, if we can just add a `--raw` argument to the list command I think we can merge this in.

**Comment by chelm** [comment]
@pramukta done. --raw dumps out the raw kernel ids from the router

**Pull request merged**
