### PR TITLE
handle comm_open and comm_msg messages over the iopub channel

### PR DESCRIPTION
**Pull request by chelm**
adds handlers for both comm_msg and comm_open and relays the messages over the iopub socket so that the JS is capable of responding to them correctly.

### CODE REVIEW

**Comment by chelm** [comment]
@pramukta we'll need this one merged and then we'll need update the package in pypi for comms support

**Comment by pramukta** [comment]
Looks good to me @chelm, were there some notes/references about the `_publish_msg` private method usage we could put in to help us in case that changes in ipython?  otherwise can just merge.

**Comment by chelm** [comment]
@pramukta sure I'll add a comment on why we use that method

**Comment by chelm** [comment]
@pramukta added a note for safe keeping

**Pull request merged**
